# Generated by Django 5.2 on 2025-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.TextField(blank=True, default=''),
        ),
    ]
