# Generated by Django 5.2 on 2025-04-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_blockedtimeslot_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
