# Generated by Django 5.2 on 2025-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_workinghours_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='awards',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
