# Generated by Django 5.2 on 2025-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_doctor_awards_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='response_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_requested', 'Appointment Requested'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_completed', 'Appointment Completed'), ('appointment_canceled', 'Appointment Canceled')], max_length=50),
        ),
    ]
