# Generated by Django 5.2 on 2025-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_requested', 'Appointment Requested'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_completed', 'Appointment Completed'), ('appointment_canceled', 'Appointment Canceled'), ('appointment_rescheduled', 'Appointment Rescheduled')], max_length=50),
        ),
    ]
