# Generated by Django 5.2 on 2025-04-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_timeslot_status'),
        ('appointments', '0010_notification_priority_alter_notification_type'),
    ]

    operations = [
    ]
