# Generated by Django 5.2 on 2025-04-19 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('message', 'Message'), ('review', 'Review'), ('system', 'System')], max_length=20)),
                ('related_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='appointment_recipie_544206_idx'), models.Index(fields=['is_read'], name='appointment_is_read_a1cc4e_idx')],
            },
        ),
    ]
