# Generated by Django 5.2 on 2025-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_workinghours_unique_together_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='appointment_duration',
            field=models.IntegerField(default=30, help_text='Duration of each appointment in minutes'),
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
    ]
