# Generated by Django 5.2 on 2025-05-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_workinghours_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='workinghours',
            index=models.Index(fields=['doctor', 'day_of_week', 'is_active'], name='appointment_doctor__94199a_idx'),
        ),
        migrations.AddIndex(
            model_name='workinghours',
            index=models.Index(fields=['doctor', 'start_time'], name='appointment_doctor__21ba9d_idx'),
        ),
    ]
