# Generated by Django 5.2 on 2025-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_workinghours_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('regular', 'Regular Checkup'), ('follow_up', 'Follow-up Visit'), ('consultation', 'Consultation'), ('emergency', 'Emergency'), ('video', 'Video Consultation'), ('specialist', 'Specialist Visit')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_video_consultation',
            field=models.BooleanField(default=False),
        ),
    ]
