# Generated by Django 5.2 on 2025-05-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_doctorpatientnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(help_text='Time slot in HH:MM-HH:MM format', max_length=15),
        ),
    ]
